fix: update NODE_PATH env vars to prevent ESLint to fails
```
export { Error: Failed to load plugin vue: Cannot find module 'eslint-plugin-vue'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at Plugins.load (/home/kocal/Dev/yProx-cli/node_modules/eslint/lib/config/plugins.js:96:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (/home/kocal/Dev/yProx-cli/node_modules/eslint/lib/config/plugins.js:157:21)
    at loadFromDisk (/home/kocal/Dev/yProx-cli/node_modules/eslint/lib/config/config-file.js:506:35)
    at Object.load (/home/kocal/Dev/yProx-cli/node_modules/eslint/lib/config/config-file.js:564:20)
    at Config.getLocalConfigHierarchy (/home/kocal/Dev/yProx-cli/node_modules/eslint/lib/config.js:227:44)
    at Config.getConfigHierarchy (/home/kocal/Dev/yProx-cli/node_modules/eslint/lib/config.js:179:43)
    at Config.getConfigVector (/home/kocal/Dev/yProx-cli/node_modules/eslint/lib/config.js:286:21)
  code: 'MODULE_NOT_FOUND',
  messageTemplate: 'plugin-missing',
  messageData: 
   { pluginName: 'eslint-plugin-vue',
     eslintPath: '/home/kocal/Dev/yProx-cli/node_modules/eslint' } }
```